# Development Docker Compose - Simplified version for testing
version: '3.9'

services:
  # Databases
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: llmoptimizer
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: llmoptimizer
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Auth Service (pre-built)
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-in-production
      - POSTGRES_URL=postgresql+asyncpg://admin:admin123@postgres:5432/llmoptimizer
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://admin:admin123@mongodb:27017/llmoptimizer?authSource=admin
    depends_on:
      - postgres
      - redis
      - mongodb
    volumes:
      - ./auth-service:/app
    command: python main_complete.py

volumes:
  mongodb_data:
  redis_data:
  postgres_data: