apiVersion: v1
kind: ConfigMap
metadata:
  name: llmoptimizer-config
  namespace: llmoptimizer
data:
  # Common configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  
  # Service URLs (internal)
  AUTH_SERVICE_URL: "http://auth-service:8000"
  CONTENT_SERVICE_URL: "http://content-service:8000"
  ANALYTICS_SERVICE_URL: "http://analytics-service:8000"
  ML_SERVICE_URL: "http://ml-service:8000"
  
  # Database URLs
  MONGODB_URL: "mongodb://mongodb:27017"
  REDIS_URL: "redis://redis:6379"
  POSTGRES_URL: "postgresql://llmoptimizer:llmoptimizer123@postgres:5432/llmoptimizer"
  
  # Token expiration
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"
  
  # Cache settings
  CACHE_TTL: "3600"
  
  # ML settings
  MODEL_CACHE_DIR: "/app/models"
  MAX_CONTENT_LENGTH: "50000"

---
apiVersion: v1
kind: Secret
metadata:
  name: llmoptimizer-secrets
  namespace: llmoptimizer
type: Opaque
stringData:
  # JWT Secret (change in production)
  SECRET_KEY: "your-super-secret-key-change-in-production"
  
  # Database credentials
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin123"
  POSTGRES_USER: "llmoptimizer"
  POSTGRES_PASSWORD: "llmoptimizer123"
  
  # API Keys (add your actual keys)
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  HUGGINGFACE_API_KEY: ""