# ServiceMonitors for application services
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  namespace: llmoptimizer
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service
  namespace: llmoptimizer
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: auth-service
  endpoints:
  - port: metrics
    interval: 30s
    path: /api/v1/metrics
    scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: content-service
  namespace: llmoptimizer
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: content-service
  endpoints:
  - port: metrics
    interval: 30s
    path: /api/v1/metrics
    scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: analytics-service
  namespace: llmoptimizer
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: analytics-service
  endpoints:
  - port: metrics
    interval: 30s
    path: /api/v1/metrics
    scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-service
  namespace: llmoptimizer
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: ml-service
  endpoints:
  - port: metrics
    interval: 30s
    path: /api/v1/metrics
    scheme: http
---
# ServiceMonitors for infrastructure components
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-component-monitor
  namespace: istio-system
  labels:
    prometheus: kube-prometheus
spec:
  jobLabel: istio
  targetLabels: [app]
  selector:
    matchExpressions:
    - {key: istio, operator: In, values: [pilot]}
  namespaceSelector:
    matchNames:
    - istio-system
  endpoints:
  - port: http-monitoring
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-stats-monitor
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
spec:
  jobLabel: envoy-stats
  selector:
    matchExpressions:
    - {key: app, operator: Exists}
  namespaceSelector:
    matchNames:
    - llmoptimizer
    - istio-system
  endpoints:
  - path: /stats/prometheus
    targetPort: 15090
    interval: 15s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'
    - action: labelmap
      regex: "__meta_kubernetes_pod_label_(.+)"
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod
---
# PodMonitors for specific workloads
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: llmoptimizer-pods
  namespace: llmoptimizer
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      monitoring: enabled
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
---
# ServiceMonitor for Node Exporter
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
# ServiceMonitor for kube-state-metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: kube-state-metrics
  endpoints:
  - port: http-metrics
    interval: 30s
    honorLabels: true
  - port: telemetry
    interval: 30s